apiVersion: v1
kind: ServiceAccount
metadata:
    name: testa1-second
---
apiVersion: v1
kind: Service
metadata:
  name: testa1-second
  labels:
    app: testa1-second
spec:
  ports:
  - port: 9986
    targetPort: 9998   
    name: http
  selector:
    app: testa1-second
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testa1-second-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testa1-second
  template:
    metadata:
      labels:
        app: testa1-second
        version: v1
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
      - name: testa1-second
        image: beaconacr.azurecr.io/beacondt:test       
        resources:
          requests:
            cpu: 100m
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /opt/matlab/licenses
            name: licenses
      - name: a1pe
        image: timfa/a1pe:beacon       
        resources:
          requests:
            cpu: 100m
        imagePullPolicy: Always
        ports:
        - containerPort: 9998
      imagePullSecrets:
        - name: beacon
        - name: foster
      volumes:
      - name: licenses
        persistentVolumeClaim:
          claimName: licenses-pv-claim
